// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package activity_database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Activity struct {
	ID              uuid.UUID
	CreatorID       uuid.UUID
	Title           string
	Description     *string
	StartTime       time.Time
	EndTime         *time.Time
	MaxParticipants *int32
	Visibility      string
	Latitude        float64
	Longitude       float64
	Location        *string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type ActivityMember struct {
	ActivityID uuid.UUID
	UserID     uuid.UUID
	Role       string
	JoinedAt   time.Time
}

type User struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	DisplayName  string
	AvatarUrl    sql.NullString
	Bio          sql.NullString
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}
