// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package user_database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Activity struct {
	ID              uuid.UUID
	CreatorID       uuid.UUID
	Title           string
	Description     sql.NullString
	StartTime       time.Time
	EndTime         sql.NullTime
	MaxParticipants sql.NullInt32
	Visibility      sql.NullString
	Latitude        float64
	Longitude       float64
	Location        string
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
}

type ActivityMember struct {
	ActivityID uuid.UUID
	UserID     uuid.UUID
	Role       sql.NullString
	JoinedAt   sql.NullTime
}

type User struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	DisplayName  string
	AvatarUrl    *string
	Bio          *string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Sex          sql.NullString
	Age          sql.NullInt32
	AvatarData   []byte
}
