// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package user_database

import (
	"database/sql"
)

type UserTable struct {
	ID               int32
	Username         string
	Name             string
	Sex              string
	Age              int32
	HashPass         string
	Email            string
	ImagePath        sql.NullString
	CreatedTimestamp sql.NullTime
}
